reg_map:
	python3 test/test.py -e -r --test tb_reg_map --in test/tb/tb_reg_map.vhd reg_map.vhd

alu:
	python3 test/test.py -e -r --test tb_alu --in test/tb/tb_alu.vhd alu.vhd

clean:
	rm -v *.cf *.o tb_reg_map tb_alu
